Imports System

Namespace Cocktail
    Public Class CocktailShaker
        Private _numArr As Integer()
        Private _arrSize As Integer

        Public Sub New()
            Dim input As String() = Console.ReadLine().Split(" "c, StringSplitOptions.RemoveEmptyEntries)
            _arrSize = input.Length
            _numArr = New Integer(_arrSize - 1) {}

            For i = 0 To _arrSize - 1
                _numArr(i) = Convert.ToInt32(input(i))
            Next
        End Sub

        Private Sub Swap(ByRef a As Integer, ByRef b As Integer)
            Dim temp = a
            a = b
            b = temp
        End Sub

        Public Sub CocktailShakerSort()
            Dim isSwapped = False
            Dim size As Integer = _arrSize / 2

            For i = 0 To size - 1

                For j = i To _arrSize - i - 2

                    If _numArr(j) > _numArr(j + 1) Then
                        Swap(_numArr(j), _numArr(j + 1))
                        isSwapped = True
                    End If
                Next

                For j = _arrSize - i - 2 To i + 1 Step -1

                    If _numArr(j - 1) > _numArr(j) Then
                        Swap(_numArr(j - 1), _numArr(j))
                        isSwapped = True
                    End If
                Next

                If Not isSwapped Then Exit For
            Next
        End Sub

        Public Sub PrintArray()
            For Each i In _numArr
                Console.Write($"{i} ")
            Next

            Console.WriteLine()
        End Sub
    End Class

    Public Module MainApp
        Public Sub Main()
            Dim s As CocktailShaker = New CocktailShaker()
            s.PrintArray()
            s.CocktailShakerSort()
            s.PrintArray()
        End Sub
    End Module
End Namespace

' 
' Input:
' 5 4 3 2 1
' 
' Output:
' 5 4 3 2 1
' 1 2 3 4 5
' 
' Note: This source code is generated by converter.